### ISSUE TITLE
API - Sources

### ISSUE THREAD

**Issue by andrei1058** [endrealm/Enhanced-Slime-World-Manager#10]
**Is your feature request related to a problem? Please describe.**
Developers can't get the sources list using the API and see which one is enabled. (If my users choose to load a world from mysql on my minigame I want to see first if eswm mysql is connected first.)

**Describe the solution you'd like**
Implement source related utils.

**Comment by Gerolmed** [comment]
Sounds like a good idea to me. I'll sit down do that. List of source objects or a list of source names?

**Comment by andrei1058** [comment]
I think we should create objects since they should have isEnabled/ isConnected methods. And since some sources may have custom methods we should use an interface.

**Comment by Gerolmed** [comment]
There is a source interface. You can implement that to add custom sources. We could add the method is active.

Is connected is quite difficult to implement with MongoDB. Afaik you have to wait for a timeout to see if its connected.

**Comment by Gerolmed** [comment]
Correcture this is already possible by checking if #getLoader(String) returns null.
Adding constants for default datasources to SlimeLoader should be a thing though
